---
version: '2.2'
services:

  axon-server:
    image: axoniq/axonserver:4.6.3
    container_name: axon
    ports:
      - "8024:8024"
      - "8124:8124"
    mem_limit: 400m
    restart: always
  redpanda:
    image: vectorized/redpanda:v22.2.2
    container_name: redpanda
    ports:
      - "9092:9092"
      - "9644:9644"
      - "29092:29092"
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --mode=dev-container
    restart: always

